### ISSUE TITLE
Leftover JMP ui issues

### ISSUE THREAD

**Issue by aymanhab** [aymanhab/opensim-gui-rcnl#1]
### List of leftover issues

- [x] Deletion is not supported in PropertyLists, either update there or workaround thoug hworkaround will have to be duplicated in a multitude of places
- [x] Serialization from XML is not working as expected
- [x] Some checkboxes are lost on round-trip
- [ ] Populate time bounds from trc file
- [ ] finalize name of plugins/dlls/repo

### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
@cvhammond This is getting close to functional. Some loose ends to address, need your feedback:
1. Inconsistent inputs (e.g. frame rotation or translations are checked but the value is 0. or marker file is unspecified, or tasks that have duplicate names or contain no joints etc.)
2. As of now "Run" button, kept for consistency with other tools does nothing, what's the plan long term for your release. 
3.  Help button needs hookup to a page of yours

You may want to get feedback from BJ or respond on email if github is not your preferred medium and you want others involved in the discussion.

**Comment by cvhammond** [comment]
1. JMP should be robust to rotations/translations being all 'false' but still included. Marker file not specified will throw error on MATLAB side. Duplicate task names don't matter, no joint tasks... I'd have to check but I think would just proceed to the next task, but they might throw error.
2. The 'Run' button hopefully runs a shell command, if possible: something like `matlab -r *load project* *JointModelPersonalizationTool("settings.xml")*` I can send you the specific command when we are ready.
3. We will have a big tutorial/example push when we are done with the hard development. I may have forgotten, but what was your recommendation on where to include the tutorials/docs?

**Comment by aymanhab** [comment]
last bullet is separate issue #14 while the last one is ongoing not a bug until we finalize plans. Closing..
