### ISSUE TITLE
[Enhancement] JMP QOL requests

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#10]
**Request 1)** 
_Set time range automatically when loading a marker file._ Currently, the time range is automatically set as -infinity to infinity, which does not work with JMP. 

**Request 2)**
_Do not highlight output model file box red when the output file does not exist._ JMP creates its own model files, therefore it's expected that the output file does not exist. Highlighting the box red seems to indicate an issue to the user, but there is no issue with writing in a file that doesn't yet exist. 

Image showing the red highlighted box.
![image](https://github.com/aymanhab/opensim-gui-rcnl/assets/142843461/7a6387bf-e7e9-4ebf-ad9f-69277772916d)

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
Separated into issues #14, #19 to be addressed independently.

**Comment by aymanhab** [comment]
closing as individual issues address same concern
