### ISSUE TITLE
[Enhancement] Add group filtering in MTP & NCP

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#11]
**Request 1)**
_Implement a filtering feature for selection prompts._ The process of reading through every group in the osim model is tedious and a user is likely to miss a group.

![image](https://github.com/aymanhab/opensim-gui-rcnl/assets/142843461/e9cac55c-2c53-4f89-9e81-53f97e3a7cf0)

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
closing as fixed, PR merged
