### ISSUE TITLE
[Enhancement] GCP QOL requests

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#12]
**Request 1)**
_When searching for IK and GRF data, set file type filter to both .sto and .mot files._ The NMSM pipeline preprocessing outputs IK and GRF data as .sto files, and the current GUI implementation ignores them, requiring the user to remove the file type filter. 

GUI with file type filter:
![image](https://github.com/aymanhab/opensim-gui-rcnl/assets/142843461/18626d87-4113-4a20-9800-4fb426c74ca1)

GUI without file type filter:
![image](https://github.com/aymanhab/opensim-gui-rcnl/assets/142843461/cac5fed8-39de-4b2c-80fe-b0fbf0136283)

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
fixed
