### ISSUE TITLE
[Enhancement] Better Installation Instructions Needed

### ISSUE THREAD

**Issue by bfregly** [aymanhab/opensim-gui-rcnl#13]
Here are steps that work for installation:

1. You need the C++ plugin because it defines all the classes used by the GUI. After logging in to Github, you can download it from here:
https://github.com/rcnl-org/nmsm-gui/releases/tag/nmsm_01
(rcnlPlugin.dll) you have to tell your browser to trust it otherwise it may refuse to download.
2. Create a folder called "plugins" in your OpenSim directory (e.g., C:\OpenSim 4.5\plugins) and place the dll in this folder.
3. When you open the OpenSim GUI, the dll now should show under Tools->User Plugins, choose it and select to always load on entry.
4. To verify that the last step worked, open the help->XMLBrowser dialog and you should be able to choose JMPBody or JMPTask from the drop down menu and see the corresponding XML layout.
5. Download the plugin jar file from
https://github.com/aymanhab/opensim-gui-rcnl/releases
and put the file someplace OTHER THAN within the OpenSim directory structure. A good place is your local Downloads folder.
7. Change to the OpenSim bin folder (e.g., C:\OpenSim 4.5\bin) and type 
>opensim64 --reload ${fullpath_to_jar_file_including_jar_file_name}
For example,
>opensim64 --reload C:\Users\bjf5\Downloads\org-opensim-rcnl.jar
8. The following messages are normal and are not errors:
The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
11.The menu items for the new tools should now be visible on the OpenSim Tools menu.
Note that you have to have an existing model loaded to proceed/use the tools, otherwise it will complain that there's no model to personalize.

**Comment by aymanhab** [comment]
@bfregly Thanks for the detailed steps, do you have a place where developer instructions are listed so we can add the steps there?  I can add them to the readme file in this repo but wonder how others will find it.

**Comment by aymanhab** [comment]
Will close, please reopen if instructions on release note here are lacking.
https://github.com/aymanhab/opensim-gui-rcnl/releases
