### ISSUE TITLE
[BUG] MTP & NCP coordinate list filter not working

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#27]
### Steps to reproduce
Navigate to Muscle Tendon Personalization Tool > Coordinate List or Neural Control Personalization Tool > Coordinate List. 
### Expected result
The "Filter by:" text block should allow user input
### Actual result
The box is grayed out and does not allow input. 

![image](https://github.com/aymanhab/opensim-gui-rcnl/assets/142843461/38d630ba-924a-4c7c-bdda-7d7c50a2d02c)

### Versions:
Windows 11, OpenSim 4.5, Gui version 0.2

**Comment by aymanhab** [comment]
This actually was assumed to be unnecessary since the original request referred to muscle groups https://github.com/aymanhab/opensim-gui-rcnl/issues/11
however considering this latest request, will implement

**Comment by aymanhab** [comment]
PR to fix is ready
