### ISSUE TITLE
[BUG] Set default value for <task_prefixes> under <MTPSynergyExtrapolation>

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#29]
### Issue
With no default value set, MTP crashes. A good default value here is "gait".

![image](https://github.com/aymanhab/opensim-gui-rcnl/assets/142843461/31805aea-5829-4551-a9ce-fcbeca38486e)

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.2

**Comment by aymanhab** [comment]
fix included in https://github.com/rcnl-org/nmsm-gui/pull/14

**Comment by aymanhab** [comment]
@RobSalati please verify if fixed. Thank you

**Comment by RobSalati** [comment]
Fixed, thank you!
