### ISSUE TITLE
Change names of menu items

### ISSUE THREAD

**Issue by aymanhab** [aymanhab/opensim-gui-rcnl#30]
### Reported by BJ
Replace names as below
Change “Joint Optimization…” to “Joint Model Personalization…”
Change “Muscle Tendon Optimization…” to “Muscle-tendon Model Personalization…”
Change “Neural Control Optimization…” to “Neural Control Model Personalization…”
Change “Ground Contact Optimization…” to “Ground Contact Model Personalization…”

Question: Does including the word “Model” in each of the four menu selections above make each item too long? If so, we could omit the word “Model” from each selection, but including it makes everything clearer and more consistent.
### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
The names appeared too long, much longer than other commands in the GUI, I removed the word Model as in the follow up except for the first menu (Joint Model Personalization) as it becomes same length as the rest 3-word pattern also injects the word model to be implied for subsequent commands underneath though at the expense of some inconsistency. Thoughts?

**Comment by aymanhab** [comment]
![CaptureRCNLPopup](https://github.com/aymanhab/opensim-gui-rcnl/assets/3972208/a64cb52b-decd-4d97-ad2f-ada1a444e91b)

**Comment by aymanhab** [comment]
@RobSalati

**Comment by RobSalati** [comment]
I think your proposed naming is good. It is in line with our tool acronyms (JMP, MTP, NCP, GCP), in which the only one that has "model" is JMP (joint model personalization).

**Comment by aymanhab** [comment]
fix submitted in https://github.com/aymanhab/opensim-gui-rcnl/pull/37
