### ISSUE TITLE
Settings file indentation

### ISSUE THREAD

**Issue by aymanhab** [aymanhab/opensim-gui-rcnl#33]
In GUI-generated JMP settings files, indentation is not correct at the top and bottom of the document. <JointModelPersonalizationTool> should be indented relative to <NMSMPipelineDocument Version=”1.0.0”>.

**Comment by aymanhab** [comment]
Some context is needed here since a fresh file has the correct indentation. The problem may occur downstream because of our messing around with top level xml tag to replace the standard OpenSimDocument with the custom NMSM tags instead.

**Comment by aymanhab** [comment]
@RobSalati

**Comment by RobSalati** [comment]
I'm not sure what this issue is referring to. The indentation looks fine to me.

NMSMPipelineDocument and JointModelPersonalizationTool are at the same indentation level but I think this is fine from a readability point of view.

**Comment by aymanhab** [comment]
Thanks @RobSalati
