### ISSUE TITLE
Include anatomical_markers Property in JMP settings file

### ISSUE THREAD

**Issue by aymanhab** [aymanhab/opensim-gui-rcnl#35]
In GUI-generated JMP settings files, the <anatomical_markers> field is missing, which should appear just below the marker file time range within a JMPTask

**Comment by aymanhab** [comment]
@RobSalati this tag was never mentioned before and was not in the XML specification I worked off. If this is new, should we update the version of the files for backward compatibility or just add it? If so I need an XML comment, tag, default value to add to the CPP initialization. Thank you

**Comment by cvhammond** [comment]
`<anatomical_markers>` is a dev-only element right now. It should not be added to the GUI tool. Thanks!

**Comment by aymanhab** [comment]
Should this be taken to mean don't include at all, or add to xml but do not expose in GUI? I assumed the latter  but the change can be undone if that's the team preference.

**Comment by RobSalati** [comment]
It should not be included in the xml file at all.
