### ISSUE TITLE
Treament optimization cost term GUI doesn't have edit button

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#39]
When adding cost terms to treatment optimization files, there is no "edit" button to add components. The only option is to manually type in the components. 

The constraint term GUI does correctly have an "edit" button.

Cost term GUI:
![image](https://github.com/user-attachments/assets/906ab8eb-84fb-4db1-b180-144b21b336bc)

Constraint term GUI:
![image](https://github.com/user-attachments/assets/04325458-44c4-490f-b09d-7fcc6f97fb2b)

**Comment by aymanhab** [comment]
This was actually a formatting/layout form so you may have been able to expand the dialog and see the edit button. Anyways, I updated the layout and it shows now in my local environment. Let me know if the latest uploaded jar file has this problem fixed. Thank you.

**Comment by RobSalati** [comment]
Fixed, thank you!
