### ISSUE TITLE
Minor GUI aesthetic updates

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#43]
There are some minor formatting changes to make the GUI have a consistent style.
In the top left: There is extra white space in the settings and RCNL controllers tab, which is inconsistent with other opensim tools.
In the right: Text boxes are not the same length. This is illustrated with a vertical red line to compare boxes.
![image](https://github.com/user-attachments/assets/d66eb8fe-6af8-4967-a3cb-4bbb71682f77)

**Comment by aymanhab** [comment]
Should be fixed in latest version, please confirm

**Comment by RobSalati** [comment]
The input dialogue boxes all line up with each other which looks great! 
There is a small discrepancy between the resultsDir box and the optimal control settings file box (see screenshot)
Lastly, there is extra white space in the tabs in the top left (I've underlined these in the screenshot)

Thank you for taking the time to fix these relatively minor problems.

![image](https://github.com/user-attachments/assets/5c212ca8-bd27-4321-aa88-bf41edc607fc)

**Comment by aymanhab** [comment]
As far as I can tell there're no extra spaces in tab names. In the previous iteration I had extra spacing to spread the tab handles but you wanted the space removed. The relation between the text and the space around it is not easily controlled, generally smallest width that fits the text. 
There's no alignment across panels (output and Optimal Control), I can combine the output and setting file in one panel to get alignment but I think the current layout is better. your call.

**Comment by RobSalati** [comment]
These are all minor tweaks, so if they take more effort to fix than they're worth, it's fine to keep them as is. 
Overall the GUI looks great and I'm super happy with how it turned out!
