### ISSUE TITLE
[BUG] JMP crashes when scaling bodies

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#6]
### Steps to reproduce
Create an xml file to scale a body with JMP.

### Expected result
The GUI outputs a file with xml elements <scale_body>

### Actual result
The GUI outputs a file with xml elements <scale_bodies>, resulting in a crash.

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
closing as fixed, please reopen if can't be verified in next build/release.
