### ISSUE TITLE
[BUG] MTP crashes with Synergy Extrapolation

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#7]
### Steps to reproduce
Create an MTP xml file with synergy extrapolation enabled.

### Expected result
The GUI creates an xml file with the element <residual_categorization> under <MTPSynergyExtrapolation>

### Actual result
The generated xml does not have <residual_categorization>
(include screen grabs where appropriate)

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
A couple follow up questions while fixing the code:
1. Do you prefer the XML comment to use lower case (task, trial, or subject)?
2. What is the default choice as I need to have it populated so it gets written to the file?

Thanks for the find.

**Comment by RobSalati** [comment]
1. Yes, we prefer the xml comment uses lowercase task, trial, or subject. 
2. The default choices should be trial for <synergy_extrapolation_categorization> and task for <residual_categorization>

The output xml should look like this:
    
    <synergy_extrapolation_categorization>trial</synergy_extrapolation_categorization>
    
    <residual_categorization>task</residual_categorization>

Thank you!

**Comment by aymanhab** [comment]
Fixed in latest commit, will close to reduce clutter,  please reopen if can't be verified in next release/iteration
