### ISSUE TITLE
[BUG] GCP not setting up directory hierarchy correctly

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#8]
### Steps to reproduce
Create GCP xml file with specified <input_directory> and <input_motion_file> & <input_grf_file>.

### Expected result
 <input_directory> is the full directory from root, and <input_motion_file> & <input_grf_file> are reported as subdirectories of <input_directory>

### Actual result
<input_directory>, <input_motion_file> & <input_grf_file>, therefore the parser cannot read the correct motion and force files.
Error using parseGroundContactPersonalizationSettingsTree>getGroundReactions
Java exception occurred:
java.io.IOException: Storage: Failed to open file
'C:\Users\midni\Documents\Github\nmsm-tutorial\Step-5-Ground-Contact-Personalization\preprocessed\C:\Users\midni\Documents\Github\nmsm-tutorial\Step-5-Ground-Contact-Personalization\preprocessed\GRFData\gait_1.sto'.
Verify that the file exists at the specified location.
	Thrown at Storage.cpp:186 in Storage().

	at org.opensim.modeling.opensimCommonJNI.new_Storage__SWIG_4(Native Method)

	at org.opensim.modeling.Storage.<init>(Storage.java:156)

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
To confirm, the intention here is to make <input_motion_file> & <input_grf_file> relative to <input_directory> before/after writing /reading the settings file which is consistent with the backend/matlab-code assumptions. The edge case of the user browsing for a file that doesn't actually fall under the input_direcory could cause problems, we'll have to come up wit a robust solution (e.g. Check before saving and abort saving if the directory structure/layout doesn't conform to pattern/assumption).

**Comment by RobSalati** [comment]
That is correct. 
For example, if <input_motion_file> is "C:\Users\midni\Documents\Github\nmsm-tutorial\Step-5-Ground-Contact-Personalization\preprocessed\", then <input_grf_file> should just be "GRFData\gait_1.sto".

**Comment by aymanhab** [comment]
Fixed in PR #26 closing for now to reduce clutter
