### ISSUE TITLE
[BUG] GCP loading settings file not working

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#9]
### Steps to reproduce
Open GCP GUI and load an existing GCP settings file.

### Expected result
The GUI automatically populates all fields from the given settings file. 

### Actual result
Opensim throws error "Failed to read 'int': property 'max_function_evaluations' with input '3e5': the data has been ignored" and does not populate any fields. 

### Environment and GUI version
Windows 11, Opensim 4.5, GUI version 0.1

**Comment by aymanhab** [comment]
Fixed in PR #16 closing for now to reduce clutter, reopen if not verified in the next build
